<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@page import="java.util.*" %>
<%@page import="dao.CategoryDAO" %>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Shop for electronics, apparels &amp; more using our Trendz app Free shipping &amp; COD.">
        <title>
          Trendz : A Online Shopping Site for Mobiles, Electronics, Furniture, Grocery, Lifestyle, Books &amp; More. Best Offers!
        </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
        <link href="../css/style.css" rel="stylesheet" type="text/css">
        <link rel="apple-touch-icon" sizes="180x180" href="../logos/favicon_io/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="../logos/favicon_io/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="../logos/favicon_io/favicon-16x16.png">
        <link rel="manifest" href="../logos/favicon_io/site.webmanifest">
        <script src="../js/MyScript.js" type="text/javascript"></script>
    </head>
    <body>

      <!-- Navbar start here -->
      <nav class="navbar">
        <form action="./product.jsp" method="get" id="search-form" class="nav-item">
            <img class="nav-brand" src="../logos/trendz.jpg"/>
            <!--  <input type="search" placeholder="Search Products" name="product" required/> -->
            <select class="categories" name="product" required>
	            <option value="" selected disabled>Choose Categories</option>
	            <%
	            	ArrayList<String> category = CategoryDAO.getAllCategories();
   	            	int n = category.size();
   	            	for(int itr = 0; itr < n; itr++) {
	            %>
	            <option value=<%= category.get(itr) %> ><% out.print(category.get(itr)); } %></option>
            </select>
            
            <button type="submit"><i class="bi bi-search"></i></button>
        </form>
        <div id="nav-menu">
          <a href="../index.jsp#home"><i class="bi bi-house-door-fill nav-item">Home</i></a>
          <a href="../index.jsp#contact"><i class="bi bi-telephone-fill nav-item">Contact</i></a>
          <a href="../index.jsp#about"><i class="bi bi-info-circle-fill nav-item">About</i></a>
          <% 
			String name = (String)session.getAttribute("name");
			if(name == null) {
          		out.println("<a href='./formPage.jsp'><i class='bi bi-person-fill nav-item'>Signin</i></a>");
			}
			else {
				out.println("<a href='./logout.jsp'><i class='bi bi-power nav-item'>logout</i></a>");
			}
		  %>
        </div>
      </nav>
      <!-- Navbar ends here -->

	  <!-- terms section starts -->
	  <section class="instruction">
	  <h1>Terms and Conditions</h1>
	  <p>These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.<p>

	  <ul>
	  	<li>Conditions Relating to Your Use of Trendz.in</li>
	    <li>Notice and Procedure for Making Claims of Infringement</li>
	  	<li>Notice and Procedure for Notifying Trendz.in of Objectionable Content</li>
	  </ul><br/><br/>
	  
	  <h1>Conditions Relating to Your Use of Trendz.in</h1><br/>
	  <p><b>1. Your Account</b><p>
      <p>If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorised access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorised manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update much of the information you provided us with in the Your Account area of the website. You agree and acknowledge that you will use your account on the website to purchase products only for your personal use and not for business purposes. Should you wish to order products for business purposes, please create a business account on Trendz.in/business. Trendz.in reserves the right to refuse access to the website, terminate accounts, remove or edit content at any time without notice to you</p><br/><br/>

	  <p><b>2. Privacy</b></p>
	  <p>Please review our Privacy Notice, which also governs your visit to Trendz.in, to understand our practices. The personal information / data provided to us by you during the course of usage of Trendz.in will be treated as strictly confidential and in accordance with the Privacy Notice and applicable laws and regulations. If you object to your information being transferred or used, please do not use the website.</p><br/><br/>

	  <p><b>3. E-Platform for Communication</b></p>
	  <p>You agree, understand and acknowledge that the website is an online platform that enables you to purchase products listed on the website at the price indicated therein at any time from any location. You further agree and acknowledge that Trendz is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the website. Accordingly, the contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on Trendz.in.</p><br/><br/>


	  <p><b>4. Access to Trendz.in</b></p>
	  <p>We will do our utmost to ensure that availability of the website will be uninterrupted and that transmissions will be error-free. However, due to the nature of the Internet, this cannot be guaranteed. Also, your access to the website may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction.</p><br/><br/>

	  <p><b>5. Licence for website access</b></p>
	  <p>Subject to your compliance with these Conditions of Use and payment of applicable fees, if any, Trendz Seller Services Private Limited grants you a limited licence to access and make personal use of this website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Trendz Seller Services Private Limited and / or its affiliates, as may be applicable. This licence does not include any resale or commercial use of this website or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this website or its contents; any downloading or copying of account information for the benefit of another seller; or any use of data mining, robots, or similar data gathering and extraction tools.</p><br/>
	  <p>This website or any portion of this website (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of Trendz Seller Services Private Limited and / or its affiliates, as may be applicable.</p><br/>
	  <p>You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Trendz.in and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilising Trendz Seller Services Private Limited's or its affiliates' names or trademarks without the express written consent of Trendz Seller Services Private Limited and / or its affiliates, as applicable. Any unauthorised use terminates the permission or license granted by Trendz Seller Services Private Limited and / or its affiliates, as applicable.</p><br/>
	  <p>You are granted a limited, revocable, and non-exclusive right to create a hyperlink to the Welcome page of Trendz.in as long as the link does not portray Trendz Seller Services Private Limited, Trendz.in, their affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Trendz.in logo or other proprietary graphic or trademark as part of the link without express written consent of Trendz Seller Services Private Limited and / or its affiliates, as may be applicable.</p><br/><br/>

	  <p><b>6. Your Conduct</b></p>
	  <p>You must not use the website in any way that causes, or is likely to cause, the website or access to it to be interrupted, damaged or impaired in any way You understand that you, and not Trendz.in, are responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only. You must not use the website for any of the following:</p><br/>
	  <ul>
		<li><p>for fraudulent purposes, or in connection with a criminal offense or other unlawful activity</p><br/></li>
		<li><p>to send, use or reuse any material that does not belong to you; or is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, insulting or harassing, blasphemous, defamatory, libelous, obscene, pornographic, paedophilic, or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, patent, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, defence, security or sovereignty of India or friendly relations with foreign States or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam; or is patently false and untrue.</p><br/></li>
		<li><p>to cause annoyance, inconvenience or needless anxiety</p><br/></li>
	  </ul><br/><br/>

	  <p><b>7. Reviews, comments, communications and other content</b></p>
	  <p>Users of this website may post reviews, comments and other content; send communications; and submit suggestions, ideas, comments, questions, or other information, as long as the content is not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties, or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." In the event a user uses a false e-mail address, impersonates any person or entity, or otherwise misleads as to the origin of any content. Trendz.in reserves the right (but not the obligation) to remove, refuse, delete or edit any content that in the sole judgement of Trendz.in violates these Conditions of use and, or terminate your permission to access or use this website.</p><br/>
	  <p>If you do post content or submit material, and unless we indicate otherwise, you<p><br/>

	  <ul>
	  	<li><p> grant Trendz Seller Services Private Limited and its affiliates a non-exclusive, royalty-free, irrevocable, perpetual and fully sublicensable rights to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media; and</p><br/></li>
	  	<li><p> Trendz Seller Services Private Limited and its affiliates and sublicensees the right to use the name that you submit in connection with such content, if they choose.</p><br/></li>
	  </ul><br/>
	  <p>You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. You agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Trendz Seller Services Private Limited, including the execution of deeds and documents, at its request.</p><br/>
	  <p>You represent and warrant that you own or otherwise control all of the rights to the content that you post or that you otherwise provide on or through the website; that, as at the date that the content or material is submitted to Trendz.in: (i) the content and material is accurate; (ii) use of the content and material you supply does not breach any applicable Trendz.in policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory); (iii) the content is lawful. You agree to indemnify Trendz Seller Services Private Limited and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.</p><br/><br/>

	  <h1>8. Claims against Objectionable Content</h1>
	  <p>You can refer to the product detail page on Trendz.in for checking any product details provided by the seller regarding the following:</p><br/>
	  <ul>
	  	<li><p>the total price in single figure of any good or service, along with the breakup price for the good or service, showing all the compulsory and voluntary charges such as delivery charges, postage and handling charges, conveyance charges and the applicable tax, as applicable. These details are available on the invoice issued to you. To understand how to generate an invoice you can refer here.</p><br/></li>
	  	<li><p>mandatory notices and information provided by applicable laws, and the expiry date of the good being offered for sale, where applicable; .</p><br/></li>
	  	<li><p>goods and services offered for sale by the seller including country of origin which are necessary for enabling the consumer to make an informed decision at the pre-purchase stage; .</p><br/></li>
		<li><p>importer and the guarantees related to the authenticity or genuineness of the imported products; and.</p><br/></li>
		<li><p>guarantees or warranties applicable to such goods or services. .Further, all contractual information required to be disclosed by law is incorporated as part of the Trendz Services Business Solutions Agreement (BSA) executed by each seller on Trendz.in, prior to listing its products. A copy of the BSA is available here.</p><br/></li>
		<li><p>Because Trendz.in lists millions of products for sale offered by sellers on the website and hosts many thousands of comments, it is not possible for us to be aware of the contents of each product listed for sale, or each comment or review that is displayed. Accordingly, Trendz.in operates on a "notice and takedown" basis. If you believe that any content on the website is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, insulting or harassing, blasphemous, defamatory, libelous, obscene, pornographic, paedophilic, invasive of another’s privacy or menacing; ethnically objectionable, disparaging; or in breach of a third party’s confidential, proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, defence, security or sovereignty of India or friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or in insulting other nation; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource; or is patently false and untrue (" Objectionable Content "), please notify us immediately by following our Notice and Procedure for Making Claims of Right Infringements. Once this procedure has been followed, Trendz.in will make all reasonable endeavours to remove such Objectionable Content complained about within a reasonable time.</p><br/></li>
	  </ul><br/><br/>
	  
	  <h1>9. Copyright, authors' rights and database rights</h1>
	  <p>All content included on the website, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of Trendz Seller Services Private Limited, its affiliates or its content suppliers and is protected by India and international copyright, authors' rights and database right laws. The compilation of all content on this website is the exclusive property of Trendz Seller Services Private Limited and its affiliates and is protected by laws of India and international copyright and database right laws. All software used on this website is the property of Trendz Seller Services Private Limited, its affiliates or its software suppliers and is protected by India and international copyright and author' rights laws.</p><br/>
	  <p>You may not systematically extract/ or re-utilise parts of the contents of the website without Trendz Seller Services Private Limited and / or its affiliate's (as may be applicable) express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this website, without Trendz Seller Services Private Limited and / or its affiliate's (as may be applicable) express written consent. You may also not create and/ or publish your own database that features substantial (eg: prices and product listings) parts of this website without Trendz Seller Services Private Limited and / or its affiliate's (as may be applicable) express written consent.</p><br/><br/>

	  <h1>10. Intellectual Property Claims</h1>
	  <p>Trendz Seller Services Private Limited and its affiliates respect the intellectual property of others. If you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement, please follow our Notice and Procedure for Making Claims of Right Infringements.</p><br/><br/>

	  <h1>11. Trademarks</h1>
	  <p>Trendz.IN, Trendz, THE Trendz LOGO, AND YOU'RE DONE, 1-CLICK, EARTH'S BIGGEST SELECTION, PURCHASE CIRCLES, LISTMANIA, NEW FOR YOU, Trendz.COM, Trendz.DE, Trendz.FR, Trendz.IT, Trendz.CO.JP, Trendz.CA, Trendz HONOR SYSTEM, PAYPAGE and other marks indicated on our website are trademarks or registered trademarks of Trendz.com, Inc. or its subsidiaries (collectively "Trendz"), in the European Union and/or other jurisdictions. Trendz.in's graphics, logos, page headers, button icons, scripts and service names are the trademarks or trade dress of Trendz. Trendz's trademarks and trade dress may not be used in connection with any product or service that is not Trendz's, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Trendz. All other trademarks not owned by Trendz that appear on this website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Trendz.</p><br/><br/>

	  <h1>12. Disclaimer</h1>
	  <p>You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through the website. You further acknowledge and undertake that you will use the website to order products only for your personal use and not for business purposes. We shall neither be liable nor responsible for any actions or inactions of sellers nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between you and the sellers or manufacturers of the products.</p><br/>
	  <p>We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services and related graphics are provided as is, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any products on the website. At no time shall any right, title or interest in the products sold through or displayed on the website vest with Trendz nor shall Trendz have any obligations or liabilities in respect of any transactions on the website.</p><br/>

	  <h1>13. Indemnity and Release</h1>
	  <p>You shall indemnify and hold harmless Trendz Seller Services Private Limited, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Conditions of Use or any document incorporated by reference, or your violation of any law, rules, regulations or the rights of a third party.</p><br/>
	  <p>You hereby expressly release Trendz Seller Services Private Limited and/or its affiliates and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waiver any claims or demands that you may have in this behalf under any statute, contract or otherwise.</p><br/><br/>

	  <h1>14. Children</h1>
	  <p>Use of Trendz.in is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may use Trendz.in only with the involvement of a parent or guardian.</p><br/><br/>

	  <h1>15. Other Businesses</h1>
	  <p>Parties other than Trendz Seller Services Private Limited and its affiliates may operate stores, provide services, or sell product lines on Trendz.in. For example, businesses and individuals offer products via Marketplace. In addition, we provide links to the websites of affiliated companies and certain other businesses. We are not responsible for examining or evaluating, and we do not warrant or endorse the offerings of any of these businesses or individuals, or the content of their websites. Trendz Seller Services Private Limited does not assume any responsibility or liability for the actions, products, and content of any of these and any other third-parties. You can tell when a third-party is involved in your transactions, and we may share customer information related to those transactions with that third-party. You should carefully review their privacy statements and other conditions of use.</p><br/><br/>

	  <h1>16. Communications</h1>
	  <p>When you visit Trendz.in, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications (including transactional, promotional and/or commercial messages), from us with respect to your use of the website and/or your order placed on the website.</p><br/><br/>

	  <h1>17. Losses</h1>
	  <p>We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when you commenced using the website.</p><br/><br/>

	  <h1>18. Alteration of Service or Amendments to the Conditions</h1>
	  <p>We reserve the right to make changes to our website, policies, and these Conditions of Use at any time. You will be subject to the policies and Conditions of Use in force at the time that you use the website or that you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p><br/><br/>

	  <h1>19. Events beyond our reasonable control</h1>
	  <p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.</p><br/><br/>

	  <h1>20. Waiver</h1>
	  <p>If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.</p><br/><br/>

	  <h1>21. Governing law and Jurisdiction</h1>
	  <p>These conditions are governed by and construed in accordance with the laws of India. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Delhi.</p><br/><br/>

	  <h1>22. Our Details</h1>
	  <p>This website is operated by Trendz Seller Services Private Limited.</p><br/><br/>

	  <h1>23. Customer Complaint Details</h1>
	  <p>The details pertaining to each customer complaint lodged (including the status of the complaint and tracking details) are provided in the return e-mails which are sent back to the customers.</p><br/>

	  <h1>24. Trendz Software Terms</h1>
	  <p>In addition to these Conditions of Use, the terms found here apply to any software (including any updates or upgrades to the software and any related documentation) that we make available to you from time to time for your use in connection with Trendz Services (the "Trendz Software").</p><br/>
	</section>
	  <!-- terms section ends -->

	  <!-- Footer starts here -->
      <footer id="about">
      	<div class="left">
	      	<h1>Know More...</h1>
	      	<br/>
			<a href="#"><i class="bi bi-box-arrow-up-right"></i> terms &amp; condition</a><br/>
			<a href="./privacy.jsp"><i class="bi bi-card-text"></i> privacy policy</a><br/>
			<a href="./help.jsp"><i class="bi bi-info-circle"></i> help</a><br/>
		</div>
		<div class="right">
	      	<h1>Connect with us </h1>
	      	<br/>
			<a href="https://www.facebook.com/trendzsupport"><i class="bi bi-facebook"></i> facebook</a><br/>
			<a href="https://www.instagram.com/trendzsupport"><i class="bi bi-instagram"></i> Instagram</a><br/>
			<a href="https://twitter.com/trendzsupport"><i class="bi bi-twitter"></i> twitter</a><br/>
		</div>
      </footer>
      <!-- Footer ends here -->
	</body>
</html>
